name: Cache CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-c2d37ef

      - name: prime-cache-c2d37ef
        run: echo "Cache hit? ${{ steps.cache.outputs.cache-hit }}"
