name: Cache Workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 24f1002578@ds.study.iitm.ac.in
        run: echo "Hello from required step"
